# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'NearMe' do

platform :ios, "8.1"
pod 'Canvas'

end

target 'NearMeTests' do

end

